---
- hosts: 10.0.0.156
  become: true
  gather_facts: no
  tasks:
  - name: Download long term jenkins release
    get_url: 
     url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
     dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    rpm_key:
     key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
     state: present

  - name: Install java
    yum:
     name: java-11-openjdk-devel
     state: present

  - name: Install epel release package for extra pacakages
    yum:
     name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
     state: present
     disable_gpg_check: true

  - name: Install jenkins
    yum: 
     name: jenkins
     state: latest
     skip_broken: yes

  - name: start jenkins
    service:
     name: jenkins
     state: started

  - name: enbale jenkins
    systemd:
     name: jenkins
     enabled: true

  - name: sleep for 30 seconds and continue to play
    wait_for:
     delay: 30
     port: 8080

  - name: init password jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result

  - name: print jenkins password
    debug:
     var: result.stdout
...
